const DEFAULT_SONG_COUNT = 30;
const MAX_RETRIES = 3;
const MINIMUM_SONG_COUNT = 5;
const CACHED_SONG_COUNT_LIMIT = 10;
const CACHED_SONG_COUNT_RETURNED = 4

module.exports = { MINIMUM_SONG_COUNT, CACHED_SONG_COUNT_LIMIT, CACHED_SONG_COUNT_RETURNED, DEFAULT_SONG_COUNT, MAX_RETRIES };